### ISSUE TITLE
Telemetry module

### ISSUE THREAD

**Issue by Razican** [OpenStratos/server-rs#11]
We need a serial telemetry module to be able to receive information during flight.

This task is divided in multiple tasks:

 - [ ] Telemetry protocol specification (#12)
 - [ ] Asynchronous serial writing (#13)
 - [ ] Logic - telemetry implementation (#14)
